=== Data

The data namespace contains functions related to the `data` set and data formats.

:sectnums!:

---

[[lib.data.loadDir]]
==== loadDir

Description::: Load a directory containing data that styx can handle.
Parameter Type::: Attribute Set
Parameters:::
  * `from`: The directory as a nix path.
  * `substitutions` (optional): A substitution set.
  * `extraAttrs` (optional): Extra attributes to add to every loaded data set as an attribute set.
Return::: A list of data sets.
Example:::

+
[source, nix]
----
data.drafts = loadDir {
  from = ./drafts;
  extraAttrs = { isDraft = true; };
});
----

NOTE: `loadDir` will print a warning for every file in the directory it cannot import.

---

[[lib.data.loadFile]]
==== loadFile

Description::: Load a file in a format that Styx can handle.
Parameter Type::: Attribute Set
Parameters:::
  * `dir`: The directory as a nix path.
  * `path`: The file name to load as a string.
  * `substitutions` (optional): A substitution set.
  * `extraAttrs` (optional): Extra attributes to add to every loaded data set as an attribute set.
Return::: The loaded file data set.
Example:::

+
[source, nix]
----
data.about = loadFile {
  dir  = ./pages;
  file = "about.md";
};
----

---

[[lib.data.asciidocToHtml]]
==== asciidocToHtml

Description::: Convert an asciidoc string to html text.
Parameter Type::: Standard
Parameters:::
  * `string`: A string in asciidoc format.
Return::: `string` converted to html.
Example:::

+
[source, nix]
----
asciidocToHtml "link:https://en.wikipedia.org/wiki/AsciiDoc[AsciiDoc] is fun!"
----

+
[source, html]
.Results in
----
<div class="paragraph">
<p><a href="https://en.wikipedia.org/wiki/AsciiDoc">AsciiDoc</a> is fun!</p>
</div>
----

---

[[lib.data.mardownToHtml]]
==== markdownToHtml

Description::: Convert a markdown string to html text.
Parameter Type::: Standard
Parameters:::
  * `string`: A string in markdown format.
Return::: `string` converted to html.
Example:::

+
[source, nix]
----
markdownToHtml "[Markdown](https://en.wikipedia.org/wiki/Markdown) is fun!"
----

+
[source, html]
.Results in
----
<p><a href="https://en.wikipedia.org/wiki/Markdown">Markdown</a> is fun!</p>
----

---

[[lib.data.mkTaxonomyData]]
==== mkTaxonomyData

Description::: Generate a taxonomy data structure.
Parameter Type::: Attribute Set
Parameters:::
  * `data`: A list of attribute sets to generate the taxonomy data structure from.
  * `taxonomies`: A list of taxonomies to generate the taxonomy data.
Return::: A taxonomy data structure as a property list.
Example:::

+
[source, nix]
----
data.taxonomies.posts = mkTaxonomyData {
  data = pages.posts;
  taxonomies = [ "tags" "level" ];
};
----

NOTE: Taxonomies are treated in detail in the <<Taxonomies>> section.

---

[[lib.data.sortTerms]]
==== sortTerms

Description::: Sort a list of taxonomy terms by the number of values they hold.
Parameter Type::: Standard
Parameters:::
  * `terms`: A list of taxonomy terms to sort.
Return::: The sorted list of terms.
Example:::

+
[source, nix]
----
sortTerms terms
----

---

[[lib.data.avluesNb]]
==== valuesNb

Description::: Return the number of values a taxonomy term holds.
Parameter Type::: Standard
Parameters:::
  * `term`: A taxonomy term.
Return::: The number of values the term holds.
Example:::

+
[source, nix]
----
sortTerms terms
----

:sectnums:
