=== Generation

The generation namespace contains functions related to the site generation.

:sectnums!:

---

[[lib.generation.generatePage]]
==== generatePage

Description::: Generate a page source by applying the `template` and the `layout` to a page attribute set. +
This is how styx generate pages in `generateSite`, simply evaluate `page.layout (page.template page)`.
Parameter Type::: Standard
Parameters:::
  * `page`: A page attribute set defining at least `template` and `layout`.
Return::: The generated static site.
Example:::

+
[source, nix]
----
generatePage {
  layout = template: "<html><body>${template}</body></html>";
  template = page: ''
    <h1>Styx example page</h1>
    ${page.content}
  '';
  content = "<p>Hello world!</p>";
};
----

+
[source, html]
.Results in
----
<html><body><h1>Styx example page</h1>
<p>Hello world!</p></body></html>
----

---

[[lib.generation.generateSite]]
==== generateSite

Description::: Generate a static site.
Parameter Type::: Attribute Set
Parameters:::
  * `pagesList` (optional): A list of page attribute sets to generate.
  * `files` (optional): A list of folders. All the contents of the folders in this list will be copied to the generated site root.
  * `substitutions` (optional): A substitution set to apply on every generated text file.
  * `preGen` (optional): A list of shell commands to run before the site is generated as a string or multiline string.
  * `postGen` (optional): A list of shell commands to run after the site is generated as a string or multiline string.
Return::: The generated static site.
Example:::

+
[source, nix]
----
generateSite { pagesList = [ pages.index ]; }
----

---

[[lib.generation.pagesToList]]
==== pagesToList

Description::: Convert the `pages` attribute set to a list of pages attribute sets.
Parameter Type::: Standard
Parameters:::
  * `pages`: The `pages` attribute set.
Return::: A list of pages attribute sets.
Example:::

+
[source, nix]
----
pagesList = pagesToList pages;
----

---

:sectnums:

