=== Generation

The generation namespace contains functions related to the site generation.

:sectnums!:

---

[[lib.generation.generatePage]]
==== generatePage

Description::: Generate a page source by applying the `template` and the `layout` to a page attribute set. +
This is how styx generate pages in `generateSite`, simply evaluate `page.layout (page.template page)`.
Parameter Type::: Standard
Parameters:::
  * `page`: A page attribute set defining at least `template` and `layout`.
Return::: The generated static site.
Example:::

+
[source, nix]
----
generatePage {
  layout = template: "<html><body>${template}</body></html>";
  template = page: ''
    <h1>Styx example page</h1>
    ${page.content}
  '';
  content = "<p>Hello world!</p>";
};
----

+
[source, html]
.Results in
----
<html><body><h1>Styx example page</h1>
<p>Hello world!</p></body></html>
----

---

[[lib.generation.generateSite]]
==== generateSite

Description::: Generate a static site.
Parameter Type::: Attribute Set
Parameters:::
  * `name` (optional): The derivation name, defaults to `styx-site`.
  * `meta` (optional): The derivation meta attributes, defaults to `{}`.
  * `files` (optional): A list of folders. All the contents of the folders in this list will be copied to the generated site root.
  * `pagesList` (optional): A list of page attribute sets to generate.
  * `substitutions` (optional): A substitution set to apply on every generated text file.
  * `preGen` (optional): A list of shell commands to run before the site is generated as a string or multiline string.
  * `postGen` (optional): A list of shell commands to run after the site is generated as a string or multiline string.
  * `genPageFn` (optional): Function to generate the page with type `Page -> String`, defaults to `generatePage`.
  * `pagePathFn` (optional): Function to generate the page path with type `Page -> String`.
+
[source, nix]
.Default implementation
----
page: page.path
----

Return::: The generated static site.
Example:::

+
[source, nix]
----
generateSite { pagesList = [ pages.index ]; }
----

---

[[lib.generation.pagesToList]]
==== pagesToList

Description::: Convert the `pages` attribute set to a list of pages attribute sets.
Parameter Type::: Attribute Set
Parameters:::
  * `pages`: The `pages` attribute set.
  * `default` (optional): An attribute set containing default page values, defaults to `{}`.
Return::: A list of pages attribute sets.
Example:::

+
[source, nix]
----
pageslist = pagestolist { inherit pages; };
----

+
[source, nix]
----
pageslist = pagestolist {
  inherit pages;
  default.layout = templates.layout;
};
----

---

:sectnums:

