=== nixpkgs

The nixpkgs namespace contains the link:https://github.com/NixOS/nixpkgs[nixpkgs] library and the nix link:http://nixos.org/nix/manual/#ssec-builtins[builtins]. +
This library contains many useful functions.

This section will be present a few commonly used function from it.

:sectnums!:

---

[[lib.nixpkgs.trace]]
==== trace

Description:: Display a variable value during site compilation.
Parameter Type:: Standard
Parameters::
  * `variable`: The variable to debug.
  * `output`: The value to output.
Return:: `output`.
Example::

+
[source, nix]
.Debugging a variable in a template
----
${trace var ""}
----

---

[[lib.nixpkgs.traceSeq]]
==== traceSeq

Description:: Display a fully evaluated variable value during site compilation.
Parameter Type:: Standard
Parameters::
  * `variable`: The variable to debug.
  * `output`: The value to output.
Return:: `output`.
Example::

+
[source, nix]
.Debugging a variable in a template
----
${traceSeq var ""}
----

CAUTION: `traceSeq` can be dangerous when used on infinite or recursive data structures so it should be used with care.

---

[[lib.nixpkgs.map]]
==== map

Description:: Apply a function to every element of a list.
Parameter Type:: Standard
Parameters::
  * `function`: Function to apply to list elements.
  * `list`: List.
Return:: The list with the function applied to every element.
Example::

+
[source, nix]
----
map (e: e * 2) [ 1 2 3 4 ]
----

+
[source, nix]
.Results in
----
[ 2 4 6 8 ]
----

NOTE: Nix being a functional language recursion is the main way to loop trhough a a list.

---

[[lib.nixpkgs.filter]]
==== filter

Description:: Filter a list.
Parameter Type:: Standard
Parameters::
  * `function`: Function to filter the list, if the function returns `true` the element is kept, if `false` the element is removed.
  * `list`: List.
Return:: The filtered list.
Example::

+
[source, nix]
----
filter (e: e > 3) [ 1 2 3 4 5 6 ]
----

+
[source, nix]
.Results in
----
[ 4 5 6 ]
----

---

:sectnums

