=== Pages

The pages namespace contains functions related to the `pages` set.

:sectnums!:

---

[[lib.pages.mkSplit]]
==== mkSplit

Description::: Generate a list of page attributes set by splitting a list of data attribute sets.
Parameter Type::: Attribute Set
Parameters:::
  * `basePath`: The base `path` set to the pages set, the first page `path` is `basePath.html`, following pages `path` is `basePath-index.html` where index is the number of the page.
  * `itemsPerPage`: The number of items per page set.
  * `data`: The list of data attribute set to split between the pages.
Return::: A list of `data` / `itemsPerPage` page attribute set with the `path` set accordingly to `basePath`.
Example:::

+
[source, nix]
----
pages.archives = mkSplit {
  basePath     = "archives";
  itemsPerPage = 10;
  data         = pages.posts;
};
----

[TIP]
====
Any extra arguments to `mkSplit` will be forwarded to every generated page set.

[source, nix]
.Set a template with mkSplit
----
pages.archives = mkSplit {
  basePath     = "archives";
  itemsPerPage = 10;
  data         = pages.posts;
  template     = templates.archives;
};
----
====

NOTE: For details see the <<Split pages>> section.

---

[[lib.pages.mkSplitCustom]]
==== mkSplitCustom

Description::: A more customizable version of `mkSplit`.
Parameter Type::: Attribute Set
Parameters:::
  * `data`: The list of data attribute set to split between the pages.
  * `head`: The settings for the first splitted page.
  ** `itemsNb`: The number of items to display on the first page.
  * `tail`: Setting for the following pages.
  ** `itemsNb`: The number of items to display per page.
  ** `basePath`: The base `path` set to the pages, the `path` is `basePath-index.html` where index is the number of the page.
Return::: A list of page attribute set according to the arguments.
Example:::

+
[source, nix]
----
pages.archives = mkSplitCustom {
  head = {
    itemsNb = 5;
    template = templates.archives.first;
  };
  tail = {
    itemsNb = 5;
    template = templates.archives.next;
  };
  data = pages.posts;
};
----

[TIP]
====
Any extra arguments to `mkSplit` will be forwarded to every generated page set. +
Any extra arguments to `head` will be forwarded to the first page set. +
Any extra arguments to `tail` will be forwarded to the rest of pages.
====

NOTE: For details see the <<Split pages>> section.

---

[[lib.pages.mkMultipages]]
==== mkMultipages

Description::: Create the list of page set for multipages data set.
Parameter Type::: Attribute Set
Parameters:::
  * `subpages`: The list of subpages source.
  * `basepath`: The base `path` set to the pages set, the first page `path` is `basepath.html`, following pages `path` is `basepath-index.html` where index is the number of the page.
  * `output`: `all`, `head` or `tail`. This select which pages set to generate.
Return::: A list of page attribute set according to the arguments.
Example:::

+
[source, nix]
----
pages.about = mkMultipages ({
  template = templates.generic.full-multipage;
  basepath = "about";
} // data.about);
----

TIP: Any extra arguments to `mkMultipages` will be forwarded to every page set.

NOTE: For details see the <<Multipages>> section.

---

[[lib.pages.mkPageList]]
==== mkPageList

Description::: Generate a list of pages attribute sets from a list of data set, but generates only the first page of multipages data set. For a use case see <<Multipages>>.
Parameter Type::: Attribute Set
Parameters:::
  * `data`: The list of data attribute set to use.
  * `pathPrefix` (optional): A prefix string to add to the generated page set `path`.
  * `multipageTemplate`: The template used for multipage data sets.
Return::: A list of page attribute set according to the arguments.
Example:::

+
[source, nix]
----
pages.posts = mkPageList {
  data = data.posts;
  pathPrefix = "posts/";
  template = templates.post.full;
  multipageTemplate = templates.post.full-multipage;
};
----

[TIP]
====
Any extra arguments to `mkPageList` will be forwarded to every generated page set.
====

NOTE: For details see the <<Multipages>> section.

IMPORTANT: For the same data set list, `basepath` set in `mkPageList` and in `mkMultiTail` **must** be the same.

---

[[lib.pages.mkMultiTail]]
==== mkMultiTail

Description::: Generate a list of multipages subpages tail page attribute sets from a list of data set. For a use case see <<Multipages>>.
Parameter Type::: Attribute Set
Parameters:::
  * `data`: The list of data attribute set to use.
  * `pathPrefix` (optional): A prefix string to add to the generated page set `path`.
Return::: A list of page attribute set according to the arguments.
Example:::

+
[source, nix]
----
pages.postsMultiTail = mkMultiTail {
  data = data.posts;
  pathPrefix = "posts/";
  template = templates.post.full-multipage;
};
----

[TIP]
====
Any extra arguments to `mkMultiTail` will be forwarded to every generated page set.
====

NOTE: For details see the <<Multipages>> section.

IMPORTANT: For the same data set list, `basePath` set in `mkPageList` and in `mkMultiTail` **must** be the same.

---

[[lib.pages.mkTaxonomyPages]]
==== mkTaxonomyPages

Description::: Generate the taxonomy related pages for the `data` list of data sets.
Parameter Type::: Attribute Set
Parameters:::
  * `data`: The list of data attribute set to use.
  * `taxonomyTemplate`: The template to use for taxonomies page sets.
  * `termTemplate`: The template to use for terms page sets.
  * `taxonomyPathFn` (optional): A function to generate the `path` of the taxonomy page with type `Taxonomy -> String`.
+
[source, nix]
.Default implementation
----
ta: "/${ta}/index.html"
----
  * `termPathFn` (optional): A function to generate the `path` of the taxonomy term page with type `Taxonomy -> Term -> String`.
+
[source, nix]
.Default implementation
----
ta: te: "/${ta}/${te}/index.html"
----
Return::: A list of page attribute set according to the arguments.
Example:::

+
[source, nix]
----
pages.postTaxonomies = mkTaxonomyPages {
  data = data.taxonomies.posts;
  taxonomyTemplate = templates.taxonomy.full;
  termTemplate = templates.taxonomy.term.full;
};
----

====
[source, nix]
.Default taxonomyPathFun
----
taxonomy: "/${taxonomy}/index.html"
----

[source, nix]
.Default termPathFun
----
taxonomy: term: "/${taxonomy}/${term}index.html"
----

CAUTION: Changing `taxonomyPathFun` or `termPathFun` will require to also update the taxonomy related template links.
====

NOTE: For details see the <<Taxonomies>> section.

---

:sectnums:
