=== Proplist

The proplist namespace contains functions to manipulate property lists, list of attribute set with only one attribute.

Property lists are used in the taxonomy data structure.

[source, nix]
.Example of a property list
----
[ { name = "Alice"; } { age = 26; } ]
----

:sectnums!:

---

[[lib.proplist.propValue]]
==== propValue

Description:: Get the value of a property.
Parameter Type:: Standard
Parameters::
  * `property`: A property.
Return:: The value of the property.
Example::

+
[source, nix]
----
propValue { name = "Alice"; }
----

+
[source, nix]
.Results in
----
Alice
----

---

[[lib.proplist.propKey]]
==== propKey

Description:: Get the key of a property.
Parameter Type:: Standard
Parameters::
  * `property`: A property.
Return:: The value of the key.
Example::

+
[source, nix]
----
propKey { name = "Alice"; }
----

+
[source, nix]
.Results in
----
name
----

---

[[lib.proplist.isDefined]]
==== isDefined

Description:: Check if a property list has a property with a specific attribute.
Parameter Type:: Standard
Parameters::
  * `attribute`: The attribute name.
  * `list`: The property list.
Return:: `true` is the property exists, `false` if not.
Example::

+
[source, nix]
----
isDefined "name" [ { name = "Alice"; } { age = 26; } ]
----

+
[source, nix]
.Results in
----
true
----

---

[[lib.proplist.getValue]]
==== getValue

Description:: Get a value from in a property list from an attribute name.
Parameter Type:: Standard
Parameters::
  * `attribute`: The attribute name.
  * `list`: The property list.
Return:: The property value.
Example::

+
[source, nix]
----
getValue "name" [ { name = "Alice"; } { age = 26; } ]
----

+
[source, nix]
.Results in
----
Alice
----

CAUTION: `getValue` will trigger an error if there is no property with the `attribute` in the list. +
`isDefined` function should be used before `getValue` to be sure the list has the `attribute`.

---

[[lib.proplist.getProp]]
==== getProp

Description:: Get a property from a property list by the attribute name.
Parameter Type:: Standard
Parameters::
  * `attribute`: The attribute name.
  * `list`: The property list.
Return:: The property.
Example::

+
[source, nix]
----
getProp "name" [ { name = "Alice"; } { age = 26; } ]
----

+
[source, nix]
.Results in
----
{ name = "Alice"; }
----

CAUTION: `getProp` will trigger an error if there is no property with the `attribute` in the list. +
`isDefined` function should be used before `getProp` to be sure the list has the `attribute`.

---

[[lib.proplist.removeProp]]
==== removeProp

Description:: Remove a property from a property list having a specific attribute name.
Parameter Type:: Standard
Parameters::
  * `attribute`: The attribute name.
  * `list`: The property list.
Return:: The property list with the property removed.
Example::

+
[source, nix]
----
removeProp "name" [ { name = "Alice"; } { age = 26; } ]
----

+
[source, nix]
.Results in
----
[ { age = 26; } ]
----

CAUTION: `removeProp` will trigger an error if there is no property with the `attribute` in the list. +
`isDefined` function should be used before `removeProp` to be sure the list has the `attribute`.

---

[[lib.proplist.propFlatten]]
==== propFlatten

Description:: Flatten a property list where multiple attributes with the same attribute are defined. Works only with property lists where the value is a list.
Parameter Type:: Standard
Parameters::
  * `list`: The property list to flatten.
Return:: The flattened property list.
Example::

+
[source, nix]
----
propFlatten [ { tags = [ "sports" "technology" ]; } { tags = [ "food" "trip" ]; } ]
----

+
[source, nix]
.Results in
----
[ { tags = [ "sports" "technology" "food" "trip" ]; } ]
----

---

[[lib.proplist.propMap]]
==== propMap

Description:: Map for property lists.
Parameter Type:: Standard
Parameters::
  * `f`: A function to apply to the property list.
  * `propList`: The property list to map.
Return:: A list.
Example::

+
[source, nix]
----
propMap (p: v: "${p}: ${v}") [ { name = "Alice"; } { age = 26; } ] 
----

+
[source, nix]
.Results in
----
[ "name: Alice" "age: 26" ]
----

---

:sectnums:

