=== Themes

This namespace contains functions related to themes.

:sectnums!:

---

[[lib.themes.loadConf]]
==== loadConf

Description::: Load themes configuration.
Parameter Type::: Attribute Set
Parameters:::
  * `themes`: A list of themes paths or packages to load configuration from.
  * `getConfFn` (optional): Function to get the configuration file with type `Theme -> Path`. +
  The path is imported with nix `import` function and in case a non-fully evaluated function is returned, it will be evaluated with `confFnArg` as an argument (default is `{}`).
+
[source, nix]
.Default implementation
----
theme: theme + "/theme.nix"
----

  * `confFnArg` (optional): If the configuration imported with `getConfFn` is a function, `confFnArg` will be passed as an argument. +
  This allows to pass arguments such as `lib` to themes configuration files for higher flexibility, defaults to `{}`.

Return::: A configuration attribute set with the `theme` and `themes` attributes. +
`theme` is the merged themes configuration, and `themes.THEME` holds the per theme default configuration.
Example:::

+
[source, nix]
----
lib.themes.loadConf { inherit themes; };
----

---

[[lib.themes.loadFiles]]
==== loadFiles 

Description::: Load themes static files.
Parameter Type::: Attribute Set
Parameters:::
  * `themes`: A list of themes paths or packages to load configuration from.
  * `getFilesFn` (optional): Function to get the theme static files directory with type `Theme -> Path`.
+
[source, nix]
.Default implementation
----
theme: theme + "/files"
----

Return::: A list of directory paths. 
Example:::

+
[source, nix]
----
files = lib.themes.loadFiles { inherit themes; };
----

---

[[lib.themes.loadLib]]
==== loadLib

Description::: Load themes libraries.
Parameter Type::: Attribute Set
Parameters:::
  * `themes`: A list of themes paths or packages to load libraries from.
  * `getLibFn` (optional): Function to get the configuration file with type `Theme -> Path`. +
  The path is imported with nix `import` function and in case a non-fully evaluated function is returned, it will be evaluated with `libFnArg` as an argument (default is `{}`). +
  If the path returned by the function does not exists, it will just be ignored and trigger no errors.
+
[source, nix]
.Default implementation
----
theme: theme: theme + "/lib/default.nix"
----

  * `confFnArg` (optional): If the configuration imported with `getConfFn` is a function, `confFnArg` will be passed as an argument. +
  This allows to pass arguments such as `lib` to themes configuration files for higher flexibility, defaults to `{}`.

Return::: An attribute set with all the themes library functions.
Example:::

+
[source, nix]
----
lib.themes.loadLib { inherit themes; libFnArg = args; };
----

---

[[lib.themes.loadTemplates]]
==== loadTemplates 

Description::: Load themes templates.
Parameter Type::: Attribute Set
Parameters:::
  * `themes`: A list of themes paths or packages to load configuration from.
  * `environment`: The default template environment.
  * `customEnvironments`: (optional) A set which attributea are template paths and the values template environments.
  * `getTemplatesFn` (optional): Function to get the theme templates directory with type `Theme -> Path`.
+
[source, nix]
.Default implementation
----
theme: theme + "/templates"
----

Return::: An attribute set containing all the themes template with their environment applied. 
Example:::

+
[source, nix]
----
templates = lib.themes.loadTemplates {
  inherit themes;
  environment = { inherit conf templates data pages lib; };
};
----

---

:sectnums:
