=== Themes

This namespace contains functions related to themes.

:sectnums!:

---

[[lib.themes.load]]
==== load

Description::: Load themes data.
Parameter Type::: Attribute Set
Parameters:::
  * `styxLib`: Styx library.
  * `themes`: A list of themes paths or packages to load data from, head of the list have lower priority.
  * `conf` (optional): configuration loading parameters:
  ** `extra` (optional): A list of base configuration attribute sets or paths, head of the list have lower priority.
  * `templates` (optional): templates loading parameters:
  ** `extraEnv` (optional): An attribute set that will be merged with the template environment.

Return::: An attribute set containing:
* `conf`: The merged themes configuration.
* `lib`: The merged themes library.
* `files`: List of static files folder.
* `templates`: The merged themes template set.
* `themes`: List of themes attribute sets.

Example:::

+
[source, nix]
----
themesData = styxLib.themes.load {
  inherit styxLib themes;
  templates.extraEnv = { inherit data pages; };
  conf.extra = [ ./conf.nix extraConf ];
};
----

---

[[lib.themes.loadData]]
==== loadData

Description::: Load a themes data.
Parameter Type::: Attribute Set
Parameters:::
  * `styxLib`: Styx library.
  * `theme`: A themes path or package to load data from.

Return::: A list of themes attribute sets containing:
* `lib`: Theme function library.
* `meta`: Theme meta information.
* `id`: Theme id.
* `path`: Theme path.
* `decls`: Theme configuration interface declarations.
* `defs`: Theme configuration interfaces definition.
* `docs`: Theme configuration interface documentation.
* `types`: Theme configuratoin interface types.
* `templates`: Theme templates functions (environment not applied).
* `files`: Theme static files path.

Example:::

+
[source, nix]
----
lib.themes.loadData {
  inherit styxLib;
  theme = styx-themes.showcase;
};
----

---

:sectnums:
