=== Utils

The utils namespace contains generic functions that do not fit in other namespaces.

:sectnums!:

---

[[lib.utils.mergeConfs]]
==== mergeConfs

Description::: Merge a list of configuration attribute sets. Sets at the beginning of the list have lower priority.

Parameter Type::: Standard
Parameters:::
  * `confs`: A list of configuration attribute sets.
Return::: The merged configuration attribute set.
Example:::

+
[source, nix]
----
conf = lib.utils.mergeConfs [
  (lib.themes.loadConf { inherit themes; })
  (import ./conf.nix)
  extraConf
];
----

---

[[lib.utils.chunksOf]]
==== chunksOf

Description::: Split a list in lists multiple lists of `n` items.
Parameter Type::: Standard
Parameters:::
  * `n`: The number of items per list.
  * `list`: the list to split.
Return::: A list of lists.
Example:::

+
[source, nix]
----
chunksOf 2 [ 1 2 3 4 5 ]
----

+
[source, nix]
.Results in
----
[ [ 1 2 ] [ 3 4 ] [ 5 ] ]
----

---

[[lib.utils.setDefault]]
==== setDefault

Description::: Set default values to a list of attribute sets.
Parameter Type::: Standard
Parameters:::
  * `list`: A list of attribute sets.
  * `default`: default values as a set.
Return::: A list of sets.
Example:::

+
[source, nix]
----
setDefault [ { foo = 1; } { bar = 2; } ] { foo = 0; bar = 0; }
----

+
[source, nix]
.Results in
----
[ { foo = 1; bar = 0; } { foo = 0; bar = 2; } ]
----

---

[[lib.utils.sortBy]]
==== sortBy

Description::: Sort a list of attribute sets by an attribute value.
Parameter Type::: Standard
Parameters:::
  * `attribute`: The attribute to use for sorting.
  * `order`: `asc` for ascding order, or `dsc` for descending order.
  * `list`: the list of attribute sets to sort.
Return::: The sorted list of attribute sets.
Example:::

+
[source, nix]
----
sortBy "priority" "asc" [ { priority = 5; } { priority = 2; } ]
----

+
[source, nix]
.Results in
----
[ { priority = 2; } { priority = 5; } ]
----

---

:sectnums:

