== Command line interface

The Styx provides a command line program `styx`.

=== Generic flags

`styx --help`:: Display the help message.
`styx --version`:: Display the version.

=== Common flags

`--in DIR`:: Run the command in `DIR`.
`--file FILE`:: Use `FILE` instead of `site.nix`.
`--drafts`:: Process and render drafts.
`--show-trace`:: Show debug output when styx command fails. (Nix flag)
`--arg NAME VALUE`:: Pass an argument `NAME` to `site.nix` main function.
`--argstr NAME VALUE`:: Pass a string argument `NAME` to `site.nix` main function.
`-I PATH`:: Add `PATH` to to the Nix expression search path, useful to use custom versions of nixpkgs.

=== New

The `new` command is used to create a site or a theme.

==== Site

The `new site` command is used to create a new Styx site.

`styx new site NAME`:: Create a Styx site in `NAME` directory in current path.
`styx new site NAME --in DIR`:: Create a Styx site in `DIR/NAME`.

==== Theme

The `new theme` command is used to create a new theme.

`styx new theme NAME --in DIR`:: Create a theme skeleton in `DIR/NAME`.


=== Build

The `build` command is used to build a Styx site.

`styx build`:: Build the Styx site and write the output in the `public` directory.
`styx build --out DIR`:: Build the nix site and write the output in the `DIR` directory.

NOTE: The `nix-build` `--show-trace`, `--arg NAME VALUE`, `--argstr NAME VALUE` and `-I PATH` flags can be used with the `build` command.


=== Preview

The `preview` command is used to launch a server that will list on localhost (127.0.0.1) port 8080 by default. The preview command will override `conf.siteUrl` to preserve links.

The server can be stopped by pressing kbd:[Ctrl+C].

`styx preview`:: Start a preview server on 127.0.0.1:8080.
`styx preview --port 9090`:: Start a preview server on 127.0.0.1:9090.
`styx preview --port 9090 --drafts`:: Start a preview server on 127.0.0.1:9090 with drafts rendered.

NOTE: Drafts are rendered only if the related logic is present in `site.nix`. The `--drafts` flag just make styx pass `extraConf.renderDrafts` as `true` to `site.nix`.


=== Live

The `live` command is similar to `preview`, with the unique difference that the site is automatically rebuilt when a change is made.

The live mode should be quitted by pressing kbd:[q].

`styx live`:: Start a live preview server on 127.0.0.1:8080.
`styx live --port 9090`:: Start a live preview server on 127.0.0.1:9090.
`styx live --port 9090 --drafts`:: Start a live preview server on 127.0.0.1:9090 with drafts rendered.

NOTE: The `live` mode does not automatically reload the browser.

WARNING: If the live mode is not quitted by pressing kbd:[q], there is a possibility that the server process will stay alive in background. The server process can be found by running `ps aux | grep caddy` and killed with the `kill` command.


=== Manual

The `manual` command can be used to launch styx HTML documentation in the default browser (`$BROWSER`).

`styx manual`:: Open the HTML help in the default browser.
`BROWSER=firefox styx manual`:: Open the HTML help in firefox.


=== Serve

The `serve` command is used to build a site and launch a local server. This allow to check the site without having to deploy it.
The server can be stopped by pressing kbd:[Ctrl+C].

`styx serve`:: Will serve on the localhost on port `8080`.
`styx-serve --port 9090`:: Will serve on the port `9090`.
`styx serve --detach`:: Will serve on the localhost on port `8080` and run the server on background, process can be found by running `ps aux | grep caddy`.

NOTE: The `nix-build` `--show-trace`, `--arg NAME VALUE`, `--argstr NAME VALUE` and `-I PATH` flags can be used with the `serve` command.

NOTE: Styx use the link:https://caddyserver.com/[caddy server], even if it is performant server, `styx serve` launchs it without any special settings. +
For production environments it is recommended to use a carefully configured server over `styx serve`.


=== Deploy

The `deploy` command is used to deploy A styx site on a remote server.
Currently only GitHub pages are supported.

For more details see the <<Deployment>> section.

`styx deploy --init--gh-pages`:: Prepare a git repository to be able to deploy on GitHub pages.
`styx deploy --gh-pages`:: Commit the Styx site in the current directory to the `gh-pages` branch in the `./gh-pages` folder.
`styx deploy --gh-pages --in ./example --out ./`:: Commit the Styx site in `./example` to the `gh-pages` branch in the `./gh-pages` folder.

