== Configuration

In a standard styx site, configuration is generated by merging multiple configuration sources (lower to higher priority):

- Themes default configuration and configuration interface (every theme `theme.nix`).
- `conf.nix` in the site root directory, the main place to configuration file.
- `site.nix` function head `extraConf` argument, used by the styx cli to override configuration keys according to passed options, mainly `siteUrl` and `renderDrafts`.

This is done in `site.nix` init section by the following code:

[source, nix]
----
  /* Configuration loading
  */
  conf = lib.utils.mergeConfs [
    (lib.themes.loadConf { inherit themes; }) # <1>
    (import ./conf.nix { inherit lib; }) # <2>
    extraConf # <3>
  ];
----

<1> Themes configuration
<2> `conf.nix`
<3> `extraConf`

=== conf.nix

`conf.nix` is the central configuration file of a styx site, its default location is in the site root.

This files consist in an attribute set defining configuration options.

The main configuration is made through themes via the `theme` attribute. +
Every theme defines some set of configuration options that can be overridden in `conf.nix` `theme` attribute.

`siteUrl` is the only required field, and must not end with a slash.

[source, nix]
.Standard conf.nix
----
{
  # URL of the site, must be set to the url of the domain the site will be deployed
  siteUrl = "http://yourdomain.com";

  # Theme specific settings
  # it is possible to override any of the theme configuration settings in the 'theme' set
  theme = {
    # Changing the theme site.title setting
    site.title = "Styx Site";
  };
}
----


[[Configuration.Meta]]
==== Meta-information

It is possible to set meta attributes that will be inherited by the site derivation. +
Beside nix derivations link:http://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes[standard meta attributes], `name` and `version` can be used to generate the derivation name in the `${meta.name}-${meta.version}` pattern.

[source, nix]
.Setting site metadata in conf.nix
----
{
  siteUrl = "http://yourdomain.com";

  meta = {
    name = "showcase-example";
    description = "Example site for the showcase site";
  };
}
----

WARNING: `meta.name` and `meta.version` must fit nix derivation naming requirements.

NOTE: In case `meta.name` and `meta.version` are not present, the site derivation name will be `styx-site`.

NOTE: A styx site derivation has `meta.platforms` set to `lib.platforms.all` by default.


[[Configuration.Customizing]]
=== Customizing configuration loading

In some cases it can be useful to make configuration files functions. +
For example, one might want to use `lib` functions in configurations file.

As `extraConf` is an attribute set provided by the styx cli command, there are two parts where it could be desirable to have configuration sets as functions:

- `conf.nix`
- themes configuration (`theme.nix`)

==== conf.nix

For `conf.nix`, passing an argument is trivial.

[source, nix]
.Passing an argument to conf.nix
----
  /* Configuration loading
  */
  conf = lib.utils.mergeConfs [
    (lib.themes.loadConf { inherit themes; })
    (import ./conf.nix { inherit lib; }) # <1>
    extraConf
  ];
----

<1> `./conf.nix` is imported and evaluated with set argument containing `lib`.

==== Themes

For themes configuration, the problem is a little different as it is possible to use multiple themes at the same time and only some of them might be functions.

Fortunately, `lib.themes.loadConf` has a `confFnArg` optional argument that can be used for that purpose. If the file loaded by `lib.themes.loadConf` for a theme is a function, it will automatically be evaluated with `confFnArg`.

The following snippet pass an argument set containing `lib` **only** to themes configuration files that are functions.

[source, nix]
.Passing an argument to themes configuration files
----
  /* Configuration loading
  */
  conf = lib.utils.mergeConfs [
    (lib.themes.loadConf { inherit themes; confFnArg = { inherit lib; }; }) # <1>
    (import ./conf.nix)
    extraConf
  ];
----

<1> Any theme `theme.nix` that is a function is evaluated with a set argument containing `lib`.

NOTE: Every theme configuration file that is a function will be evaluated with the same `confFnArg`.


