== Configuration

In a standard styx site, configuration is generated by merging multiple configuration sources (lower to higher priority):

- Themes default configuration and configuration interface (every theme `conf.nix`).
- `conf.nix` in the site root directory, the main place to configuration file.
- `site.nix` function head `extraConf` argument, used by the styx cli to override configuration keys according to passed options, mainly `siteUrl` and `renderDrafts`.

Configuration loading is done in `site.nix` theme section.


=== conf.nix

`conf.nix` is the central configuration file of a styx site, its default location is in the site root.

This files consist in an attribute set defining configuration options.

The main configuration is made through themes via the `theme` attribute. +
Every theme defines some set of configuration options that can be overridden in `conf.nix` `theme` attribute.

`siteUrl` is the only required field, and must not end with a slash.

[source, nix]
.Standard conf.nix
----
{
  # URL of the site, must be set to the url of the domain the site will be deployed
  siteUrl = "http://yourdomain.com";

  # Theme specific settings
  # it is possible to override any of the theme configuration settings in the 'theme' set
  theme = {
    # Changing the theme site.title setting
    site.title = "Styx Site";
  };
}
----


