== Deployment

=== GitHub pages

Styx support basic deployment to GitHub pages.

This is a two step process, initialization of the `gh-pages` branch and update of the `gh-branch` with the built site.

[source, bash]
.Setting a Styx site for GitHub pages
----
$ styx new site mysite && cd mysite # <1>
$ git init && git add . && git commit -m "Initializing Styx site" # <2>
$ styx deploy --init-gh-pages # <3> 
$ styx deploy --gh-pages # <4>
----

<1> Creating a new styx site and entering the new site directory.
<2> Initializing a git repository with all the files and commiting.
<3> Creating an empty `gh-pages` branch.
<4> Building the Styx site and commiting the changes to `gh-pages`

Then it is just a matter to push the `gh-pages` branch to your GitHub repository and the site will be published.

WARNING: `styx deploy --init-gh-pages` and `styx deploy --gh-pages` involve git checkouts. Every time git make a checkout, the files timestamp change.
This means that two successive `styx deploy --gh-pages` will create changes, namely every part of the Styx site that depends on the `lastChange` argument. (RSS feeds)

=== Other

Styx does not yet provide a universal deployment method, but `rsync` can be used to deploy a Styx site to a remote server via ssh.

