== Deployment

=== GitHub pages

Styx supports basic deployment to GitHub pages.

This is a two step process:

- first by preparing the repository to deploy on GitHub pages. (`deploy --init-gh-pages`)
- then by updating that branch. (`deploy --gh-pages`)

==== Initialization

The `styx deploy --init-gh-pages` command will prepare the repository for GitHub deployment. This command will do the following:

- create a `gh-pages` directory
- add the `gh-pages` folder to `.gitignore`
- clone the repository in the `gh-pages` folder
- create a new empty `gh-pages` branch in the `gh-pages` folder

==== Update the gh-pages branch

The `styx deploy --gh-pages` command will build the site, and update the `gh-pages` folder with the generated static site and commit it to the `gh-pages` branch.

Then changes can be pushed with the following commands:

[source, sh]
----
$ (cd gh-pages && git push -u origin gh-pages) # <1>
$ git push -u origin gh-pages # <2>
----

<1> Push the `gh-pages` folder `gh-pages` branch to the root repository.
<2> Push the root repository `gh-pages` branch to the remote repository.


=== NixOps

link:http://nixos.org/nixops/[NixOps] is a deployment tool for NixOS configurations, and can be used to deploy styx sites.

[[nixops-example]]
[source, nix]
.NixOps expression to deploy a styx website
----
{
  network.description = "Styx example";

  webserver = { config, pkgs, ... }: { # <1>
    deployment = { # <2>
      targetEnv = "virtualbox";
      virtualbox.memorySize = 1024;
      virtualbox.headless = true;
    };

    networking.firewall.allowedTCPPorts = [ 80 ]; # <3>

    services.nginx = { # <4>
      enable = true;
      httpConfig = ''
        server {
          listen 80;
          location / {
            root ${(pkgs.callPackage ./site.nix {}).site}; # <5>
          }
        }
      '';
    };
  };
}
----

<1> Create a machine named `webserver` for deployment.
<2> Set up deployment information, for this example deploy on a VirtualBox machine.
<3> Open port 80 on the `webserver` machine.
<4> Nginx settings.
<5> Set the Nginx root location to the styx site package. Remote repositories can be fetched with nixpkgs `fetch*` functions.

NOTE: The NixOps link:http://nixos.org/nixops/manual/[manual] provides information about all the deployment options.

Then the site can be deployed via NixOps with the following set of commands:

[source, sh]
----
$ nixops create -d styx-site nixops-expression.nix # <1>
$ nixops deploy -d styx-site # <2>
----

<1> This command creates a new NixOps deployment, the `-d` flag specify the deployment name. +
The deployment information can be queried with the `nixops info -d styx-site`. +
`nixops-expression.nix` is a file containing the nix expression for the deployment like the one showed in the <<nixops-example,example>>.
<2> This command will create the VirtualBox machine and deploy the configuration into it. +
If all goes well, the website will be available by opening the deployment machine in a browser.
The deployement machine IP can be found with the `nixops info -d styx-site`.


=== Amazon S3 Bucket

Amazon S3 buckets can be used to host static websites.
The AWS CLI tool can be used in conjunction with styx to upload a styx website to a S3 bucket.

[source, sh]
.Deploying a styx website to S3
----
$ nix-shell -p awscli

$ aws s3 sync $(styx store-path) s3://<bucket name>/
----

Site url can also be specified with the `--site-url` flag.

[source, sh]
.Deploying a styx website to S3 using a custom site-url
----
$ nix-shell -p awscli
$ aws s3 sync $(styx store-path --site-url "http://<bucket name>.s3-website-<region>.amazonaws.com") s3://<bucket name>/
----

NOTE: For a S3 website to be world accessible, link:http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteAccessPermissionsReqd.html[adjusting policies might be required].


=== Other

Styx does not yet provide a universal deployment method, but `rsync` can be used to deploy a Styx site to a remote server via ssh.

