== Site Generation

Site generation consists in a call to link:library.html#lib.generation.mkSite[`mkSite`], and the preparation of its arguments.

[source, nix]
.Standard call to mkSite
----
pagesList = pagesToList { inherit pages; }; # <1>

site = mkSite { inherit conf files pagesList; } # <2>
----

<1> Convert the pages attribute set to a list of pages.
<2> Generate the site.

It is possible to set default attributes to every page set during the `pages` attribute by using the `default` argument of the <<lib.generation.pagesToList>> function.

A typical example is setting a default layout to every page set that do not declares one.

[source, nix]
.Setting a default layout to every page set
----
pagesList = lib.pagesToList {
  inherit pages;
  default.layout = templates.layout;
};
----

NOTE: Styx expects the site to be rendered in the `site` attribute of the main set.


=== Substitutions

Subtitutions are a way to pass variables from `site.nix` in markup or static files.

Substitutions are a set that is passed to the `mkSite` function. Any value of set will be replaced in the markup or static files that `mkSite` outputs.

[source, nix]
.Simple substitution set
----
  substitutions = {
    siteUrl = conf.siteUrl;
  };

  site = lib.mkSite {
    inherit files pagesList substitutions;
  };
----

To be replaced, the variable as to be surrouded by `@`, for example `@siteUrl@`.

[source, css]
.Using a substitution in a css file
----
background: url(@siteUrl@/images/foo.png);
----

TIP: Substitutions are specially useful for resolving in-site links with `conf.siteUrl`, but they can also be used with sass or less to externalize css variables in `conf.nix`.

=== Special files

Styx automatically convert `sass`, `scss` and `less` files to css during site generation.

=== Hooks

`mkSite` provide two hooks to customize the site generation process:

- `preGen`: A string or multiline string with shell commands to run before generating the site.
- `postGen`: A string or multiline string with shell commands to run after generating the site.


=== Site derivation

Styx creates the static site as a standard nix derivation.

It is possible to set the derivation metadata by passing a `meta` set to the `mkSite` function.

[source, nix]
.Setting site derivation metadata
----
  site = with lib; mkSite {
    inherit files pagesList substitutions;
    meta = {
      license = licenses.mit;
      name = "foo-1.0.0";
    };
  };
----

