== Release Notes

:sectnums!:

[[v0.7.2]]
=== Styx 0.7.2 - 2020/06/02

==== Fixes

* caddy fails with `no bin`, removing the .bin fixes it
* proofreading 

[[v0.7.1]]
=== Styx 0.7.1 - 2018/01/26

==== Fixes

* Fixed `styx` command path resolution when styx was installed globally.


[[v0.7.0]]
=== Styx 0.7.0 - 2017/08/26

==== Highlights:

* Styx use its own version without relying on global `<nixpkgs>`, this ensure that `site.nix` format, used styx-themes and styx versions are matching.
* Instructions and helpers for <<multilocale,multi-locale>> sites.
* Block feature for flexible single page websites, used in the Agency theme.
* Better support for Darwin platforms.

==== New themes:

* Nix
* Ghostwriter

==== New commands:

* `styx preview-theme`: Preview a styx-theme theme, eg: `styx preview-theme ghostwriter`.

==== Breaking Changes:

`site.nix` format have been simplified. Required arguments are `styx` and `extraConf` only.
The themes set `styx-themes`, can be accessed with `import styx.themes` and is tied to the styx version.

[source, nix]
.Pre 0.7.0 site.nix
----
{ lib, styx, runCommand, writeText
, styx-themes
, extraConf ? {}
}@args:

rec {

  /* Importing styx library
  */
  styxLib = import styx.lib args;
----

[source, nix]
.Post 0.7.0 site.nix
----
{ styx
, extraConf ? {}
}:

rec {

  /* Importing styx library
  */
  styxLib = import styx.lib styx;


  /* Importing styx themes from styx
  */
  styx-themes = import styx.themes;
----


---
[[v0.6.0]]
=== Styx 0.6.0 - 2017/02/26

==== Highlights:

* Nix expressions can be <<data.embedded-nix,embedded>> in markup files.
* Site building perfomance improvements.

New commands:

* `styx site-doc`: generate documentation for a styx site.
* `styx gen-sample-data`: generate sample data.
* `styx linkcheck`: check the internal links of a site.

New features in the generic templates theme:

* `templates.media.*`: For embedding media. (giphy, github gists, slideshare, speakerdeck, twitter, vimeo and youtube)
* `conf.services.*`: For third party services integration. (disqus, piwik and google analytics)
* `conf.lib.*`: highlightjs, google fonts and mathjax support added.

==== Improvements

* Performance.
* Drafts can be automatically handled with metadata.
* `mkPageList` automatically handle multipage pages.
* Themes and library documentations.

==== Breaking Changes:

* Substitutions in data files have been removed in favor embedded nix. (substitutions can still be used in static files)
* `themes.load` function arguments were renamed:
** `templates.extraEnv` renamed to `extraEnv`.
** `conf.extraConf` renamed to `extraConf`.
* `loadDir` and `loadFile` functions arguments have changed.
* `mkMultiTail` function have been removed in favor of `mkPageList`.
* `loadDir` and `loadFile` functions arguments has been modified.
* `generateSite` was renamed to `mkSite` and its `pagesList` argument was renamed to `pageList`.
* `mkPageList` now outputs a pages set, with a `list` attribute containing the page list. To refer pages generated with `mkPageList` use the `list` attribute, eg `pages.posts.list`.

---

[[v0.5.0]]
=== Styx 0.5.0 - 2017/01/18

Highlights:

* New theme: link:./styx-themes.html#generic-templates[generic-templates]. The generic-templates theme provide a template framework and basic templates for common components.
* Showcase and Hyde themes have been ported to use generic-templates.
* Theme configuration interface can be typed, and site configuration is type-checked.
* `styx-themes` themes link:./styx-themes.html[full documentation].
* <<themes.metadata,Themes metadata>>.
* <<Debugging,Interactive debugging>> with `nix-repl.`
* <<site.nix,Simpler and shorter>> `site.nix`
* <<themes.library,Themes can provide function libraries>>.
* <<lib.template.parseDate,Content timestamps support time>>.

Breaking Changes:

* Many, among others:
** `site.nix` was refactored
** Themes `theme.nix` was removed, its functionality is divided in two files, `conf.nix` and `meta.nix`. `conf.nix` for configuration interface and `meta.nix` for theme metadata.
** Themes `meta.nix` file **must** be present and **must** declare a `id` attribute specifying the theme id.
** `lib.pages.setDefaultLayout` was removed (default pages values can be set with the `default` argument of <<lib.generation.pagesToList>>).
** all occurences of `href` in function names / parameters and template variables has been replaced with `path`, pages `path` attribute must start with a `/`.

Upgrading:

This release brings many incompatible changes that requires to refactor `site.nix` to upgrade. +
Changes involve, among others, the init section of `site.nix`, `site.nix` returning a set instead of a `generateSite` call and `href` occurrences replaced by `path` (`path` attributes must start with a `/`).

Comments:

This is the first close to stable release of styx. Please test and send any bug or question to the link:https://github.com/styx-static/styx/issues[bug tracker].

---

[[v0.4.0]]
=== Styx 0.4.0 - 2016/12/07

Highlights:

- Better integration with the <<NixOps,Nix ecosystem>>, styx sites can be called from nix expressions with `callPackage`
- Themes can be used from the `styx-themes` set of packages
- new `manual` subcommand to open the HTML documentation in a browser

Breaking Changes

- Removal of the `state` variable in `site.nix`
- `site.nix` init section was refactored

This release brings few major breaking changes that make upgrading from 0.3.0 non trivial. +
The main changes involve the init section of `site.nix`.

---

[[v0.3.0]]
=== Styx 0.3.0 - 2016/10/26

Highlights:

- <<Themes,Themes as first class citizens>>
- link:https://github.com/styx-static/themes[New themes]
- Styx library is automatically bundled
- <<Taxonomies>>
- <<library,New functions in library, new sub libraries>>
- <<Asciidoc,AsciiDoc support>>
- <<Multipages>>
- Easier updates

This release brings many major breaking changes that make upgrading from 0.2.0 non trivial. +
Fortunately, the new features introduced in this release should make future upgrades easy.

---

[[v0.2.0]]
=== Styx 0.2.0 - 2016/10/10

Highlights:

- Live preview mode for the cli command (<<Live>>)
- Introduction of themes (<<Themes>>)
- Content substitutions (<<Substitutions>>)
- Content metadata (<<Metadata>>)

New features:

- cli command
   - new `preview` subcommand to preview a site locally
   - new `live` subcommand to preview and automatically reload changes
   - `serve` subcommands new flags:
      - `--detach` to launch the server in a background process
      - `--server-host` to specify the server listening hostname
      - `--siteUrl` to override `conf.siteUrl`
   - new `-target` flag to specify the Styx site folder
- content substitutions (<<Substitutions>>)
- themes (<<Themes>>)
- metadata (<<Metadata>>)
- 404 error page template

Incompatible changes:

- `default.nix` was renamed to `site.nix`
- `site.nix` `previewMode` was renamed to `renderDrafts`
- cli `--preview` flag has been renamed to `--drafts`
- `lib.content`: `getPosts`, `getDrafts` and `parsePage` arguments have changed
- `lib.generation`: `generateSite` arguments have changed
- `lib.utils`: `loadTemplateWithEnv` function was removed

Bug Fixes:

- nix link in the default theme layout template
- `styx new` is working when called in empty folders
- default theme archive title is not hardcoded
- default them pagination is displayed only when there is more than one page

This release bring many major changes that make updating from 0.1.0 non-trivial.

To update, it is recommended to generate a new site, create a new theme with customized templates and static files, and update `site.nix` accordingly.

---

[[v0.1.0]]
=== Styx 0.1.0 - 2016/10/07

Initial release of Styx.

:sectnums:
