[[Themes]]
== Themes

Themes are a central concept in styx and are used to manage a site assets, like static files and templates.
They also provide a configuration interface and can declare a function library.

=== Getting themes

Styx themes are listed in the official link:https://github.com/styx-static/themes[theme repository].

Themes available at the moment of writing this documentation are:

- link:https://github.com/styx-static/styx-theme-generic-templates[Generic templates]: A theme theme provide a template framework and basic templates for common components. (link:https://styx-static.github.io/styx-theme-generic-templates/[demo site])
- link:https://github.com/styx-static/styx-theme-showcase[Showcase]: A theme that show most of styx functionalities and provides many templates. (link:https://styx-static.github.io/styx-theme-showcase/[demo site])
- link:https://github.com/styx-static/styx-theme-hyde[Hyde]: A port of the link:https://github.com/poole/hyde[Jekyll Hyde theme] to styx. Hyde is a simple and beautiful blog theme. (link:https://styx-static.github.io/styx-theme-hyde/[demo site])
- link:https://github.com/styx-static/styx-theme-agency[Agency]: A port of the link:http://themes.gohugo.io/agency/[Hugo agency theme] to styx. Agency is a single page site with a modern design fitting company or agency websites. (link:https://styx-static.github.io/styx-theme-agency/[demo site])
- link:https://github.com/styx-static/styx-theme-orbit[Orbit]: A port of the link:http://themes.gohugo.io/orbit/[Hugo orbit theme] to styx. Orbit is a single page site resume / profile theme. (link:https://styx-static.github.io/styx-theme-orbit/[demo site])

=== Creating a new theme

A new theme folder structure can be created by running the `styx new theme` command.

[source, shell]
.Creating a new theme
----
$ styx new theme my-theme --in ./themes
----

This command will generate the following files:

----
├── conf.nix   # <1>
├── meta.nix   # <2>
├── files/     # <3>
└── templates/ # <4>
----

<1> Theme configuration interface, see <<Themes.conf.nix,conf.nix>> for details.
<2> Theme meta data, see <<meta.nix>> for details.
<3> Directory to store theme static files, see <<Files>> for details.
<4> Directory to store theme templates, see <<Templates>> for details.

See <<Themes.Structure, Structure>> for details.

NOTE: Site and themes both have `conf.nix` files, their purpose is different and should not be confused. +
Theme `conf.nix` define the configuration interface, and site `conf.nix` use this configuration.

=== Using themes

Declaring used themes is done in the <<site.nix-themes,theme section>> of `site.nix`.
Official themes can be used directly from the `styx-themes` package set.

[source, nix]
.Using a local my-site theme and the generic-templates theme
----
  /* list the themes to load, paths or packages can be used
     items at the end of the list have higher priority
  */
  themes = [
    styx-themes.generic-templates
    ./themes/my-theme
  ];
----

NOTE: Items at the beginning of the `themes` list have lower priority.

[[Themes.Structure]]
=== Structure

Themes are usually stored in the `themes` directory, or used from the `styx-themes` package set.

Every theme is stored in its own directory, and themes are expected to follow a certain structure.

[source, shell]
.Structure of a Styx theme
-----
themes
└── NAME # <1>
    ├── conf.nix # <2>
    ├── meta.nix # <3>
    ├── lib.nix # <4>
    ├── files/ # <5>
    └── templates/ # <6>
-----

<1> Theme directory.
<2> `conf.nix` defines the theme configuration interface options (optional). 
<3> `meta.nix` defines the theme meta information, this is file is required and must define a `id` attribute.
<4> `lib.nix` defines the theme extra library as a set (optional).
<5> `files` is a directory holding static files for the themes. All the files in this directory will be copied in the generated site (optional).
<6> `templates` is a directory storing all the templates files (optional).


[[Themes.conf.nix]]
=== Configuration interface

A theme can provide a configuration interface by having a `conf.nix` file at the theme root directory.

In its simplest form, `conf.nix` should be an attribute set defining theme options with default values.

[source, nix]
.Example of a theme conf.nix
----
{
  site = {
    title = "The Agency";
    author = "Your name";
    description = "Your description";
  };
}
----

This configuration is merged in the `conf` variable `theme` key after theme loading, and can be used from the site configuration (site `conf.nix`).

[source, nix]
.Usage of a theme configuration option in a **site** conf.nix
----
{
  theme.site.title = "My Agency";
}
----


==== Typing

`conf.nix` can leverage NixOS module system like typing, and declare options with the `mkOption` function.

https://nixos.org/nixos/manual/index.html#sec-option-declarations

This have two benefits:

- Site configuration, site root `site.nix`, will be type checked.
- Documentation will be automatically generated for the configuration interface.

On the other hand, typing a theme configuration interface is verbose and can be an overkill for theme that will not be shared.  
Typing is not required, but should be done for themes that are part of the `styx-themes` theme set or meant to be shared.


[source, nix]
.Example of a theme conf.nix with typing
----
{ lib }:
with lib;
{
  
/* General settings
*/
  site = {
    title = mkOption {
      default = "The Agency";
      type = types.str;
      description = "Title of the site.";
    };
    author = mkOption {
      default = "Your name";
      type = types.str;
      description = "Content of the author `meta` tag.";
    };
    description = mkOption {
      default = "Your description";
      type = types.str;
      description = "Content of the description `meta` tag.";
    };
  };
}
----

Options can then be used in the site `conf.nix` in the same manner than non-typed ones.

[source, nix]
.Wrong usage of a theme configuration option in a **site** conf.nix
----
{
  theme.site.title = 2;
}
----

[source, bash]
.Trying to build a site with type errors
----
$ styx preview
error: The configuration option `theme.site.title' is not a str.
(use ‘--show-trace’ to show detailed location information)
---
Error: Site could not been built, fix the errors and run the command again.
The '--show-trace' flag can be used to show debug information.
----


=== Meta-data

Theme meta information should be declared in the `meta.nix` file as an attribute set. Themes *must* define a `meta.nix` with an `id` attribute so the theme configuration is correctly processed. +

Other attributes of the `meta` set are totally optional and can be set at will to provide information about the theme (e.g. `license`, `description`, `author`, `homepage`, ...).

[source, nix]
.Example of a simple theme meta.nix
----
{
  id = "showcase";
}
----

[source, nix]
.Example of a theme meta.nix with license and maintainers
----
{ lib }:
{
  id = "showcase";
  license = lib.licenses.mit;
  maintainers = with lib.maintainers; [ johndoe ];
}
----

IMPORTANT: Themes *must* define a `meta.nix` with an `id` attribute.

NOTE: `meta.nix` can be an attribute set or a function, if it is a function it will be called with an attribute set argument containing `lib`.

=== Files

The `files` directory holds the static files provided by the theme. Every file in in this directory will be copied in the generated site.

NOTE: If multiple themes are enabled, every theme `file` directory contents will be copied to the generated site. If this is not desirable, it is possible to pass a different list of themes to <<lib.themes.load, lib.themes.load>> function `files` argument.

==== Special files

Styx automatically convert `sass`, `scss` and `less` files to css during site generation.

[[Themes.Library]]
=== Library

Themes can provide a function library that can be used in `site.nix` or in templates.

To provide a library, a theme must have a `lib.nix` file containing an attribute set of functions.

To be sure a theme library functions will not override default functions it is best practice to put the functions in a dedicated namespace, `theme.ID` where `ID` is the theme id as a natural choice.

[source, nix]
.Example of a theme lib.nix
----
{ lib }:
{
  theme.my-theme = {
    foo = x: "foo called with ${builtins.toString x}";
  };
}
----

NOTE: `lib.nix` can be an attribute set or a function, if it is a function it will be called with an attribute set argument containing `lib`.

include::themes/templates.adoc[]


=== Combining Themes

In `site.nix`, themes are declared as a list. If multiple themes in the list provide the same file or template, the last theme in the list to declare it will be used.

This allows to build new themes based on other themes, like the showcase theme is built on the base of the generic-templates theme.

To combine a theme it is just needed to declare multiple themes in `site.nix`. If multiple themes define the same asset, asset from the later theme in the list will be used.

[source, nix]
.Combining generic-templates and my-theme
----
themes = [
  styx-themes.generic-templates
  ./themes/my-theme
];
----

If generic-templates and my-theme both defines `templates/partials/content.nix`, the one from my-theme will be used. +
Any used asset that is not defined in my-theme, will be used from generic-templates.

NOTE: There is no limit in the number of theme that can be combined.

include::themes/generic-templates.adoc[]

