[[Themes]]
== Themes

Themes are a central concept in styx and are used to manage a site assets, like static files and templates.
They can also provide a configuration interface and a function library.

=== Getting themes

Styx themes that are part of the `styx-themes` package set are documented in the link:./styx-themes.html[styx-themes documentation].


=== Creating a new theme

A new theme file structure can be created by running the `styx new theme` command.

[source, shell]
.Creating a new theme
----
$ styx new theme my-theme --in ./themes
----

This command will generate the following files in `./themes/my-theme`:

----
├── conf.nix   # <1>
├── meta.nix   # <2>
├── files/     # <3>
└── templates/ # <4>
----

<1> Theme configuration interface, see <<themes.configuration>> for details.
<2> Theme meta data, see <<themes.metadata>> for details.
<3> Directory to store theme static files, see <<themes.files>> for details.
<4> Directory to store theme templates, see <<themes.templates>> for details.

See <<themes.structure>> for details.

NOTE: Site and themes both have `conf.nix` files, their purpose is different and should not be confused. +
Theme `conf.nix` **define** the configuration interface, and site `conf.nix` settings **use** this interface to customize the theme.

=== Using themes

Declaring used themes is done in the <<site.nix-themes,theme section>> of `site.nix`.
Path or packages can be used.

[source, nix]
.Using a local my-site theme and the generic-templates theme
----
  /* list the themes to load, paths or packages can be used
     items at the end of the list have higher priority
  */
  themes = [
    styx-themes.generic-templates
    ./themes/my-theme
  ];
----

NOTE: Items at the beginning of the `themes` list have lower priority.

[[themes.structure]]
=== Structure

Themes are usually stored in a `themes` directory, or used from the `styx-themes` package set.

Every theme is stored in its own directory, and themes are expected to follow a certain structure.

[source, shell]
.Structure of a Styx theme
-----
themes
└── NAME # <1>
    ├── conf.nix # <2>
    ├── meta.nix # <3>
    ├── lib.nix # <4>
    ├── files/ # <5>
    └── templates/ # <6>
-----

<1> Theme directory.
<2> `conf.nix` defines the theme configuration interface options (optional). 
<3> `meta.nix` defines the theme meta information, this is file is **required** and **must** define a `id` attribute.
<4> `lib.nix` defines the theme extra library as a set (optional).
<5> `files` is a directory holding static files for the themes. All the files in this directory will be copied in the generated site (optional).
<6> `templates` is a directory storing all the templates files (optional).


[[themes.configuration]]
=== Configuration interface

A theme can provide a configuration interface by having a `conf.nix` file at the theme root directory.

In its simplest form, `conf.nix` should be an attribute set defining theme options with default values.

[source, nix]
.Example of a theme conf.nix
----
{
  site = {
    title = "The Agency";
    author = "Your name";
    description = "Your description";
  };
}
----

This configuration is merged in the `conf` variable `theme` key after theme loading, and can be used from the site configuration (site `conf.nix`).

[source, nix]
.Usage of a theme configuration option in a **site** conf.nix
----
{
  theme.site.title = "My Agency";
}
----


==== Typing

`conf.nix` can leverage NixOS module system like typing, and declare options with the `mkOption` function.

See link:https://nixos.org/nixos/manual/index.html#sec-option-declarations[NixOS manual option declaration chapter] for `mkOption` usage details.

This have two benefits:

- Site configuration, site root `site.nix`, will be type checked.
- Documentation will be automatically generated for the configuration interface.

On the other hand, typing a theme configuration interface is verbose and can be an overkill for a private theme. +
Typing is not required, but should be done for themes that are part of the `styx-themes` theme set or meant to be shared.

WARNING: `types.submodule` type is **not** supported.

[source, nix]
.Example of a theme conf.nix with typing
----
{ lib }:
with lib;
{
  
/* General settings
*/
  site = {
    title = mkOption {
      default = "The Agency";
      type = types.str;
      description = "Title of the site.";
    };
    author = mkOption {
      default = "Your name";
      type = types.str;
      description = "Content of the author `meta` tag.";
    };
    description = mkOption {
      default = "Your description";
      type = types.str;
      description = "Content of the description `meta` tag.";
    };
  };
}
----

Options can then be used in the site `conf.nix` in the same manner than non-typed ones.

[source, nix]
.Wrong usage of a theme configuration option in a **site** conf.nix
----
{
  theme.site.title = 2;
}
----

[source, bash]
.Trying to build a site with type errors
----
$ styx preview
error: The configuration option `theme.site.title' is not a string.
(use ‘--show-trace’ to show detailed location information)
---
Error: Site could not been built, fix the errors and run the command again.
The '--show-trace' flag can be used to show debug information.
----


[[themes.metadata]]
=== Metadata

Theme metadata is declared in the `meta.nix` file as an attribute set. Themes *must* define a `meta.nix` with an `id` attribute so the theme configuration is correctly processed. +

Other attributes of the `meta` set are totally optional and can be set at will to provide information about the theme (e.g. `license`, `description`, `author`, `homepage`, ...).

`meta` attributes used for the generated documentation are:

- `name`: Theme name, can contain any character.
- `license`: A license from `lib.licenses`.
- `demoPage`: Url of the theme example site live demo.
- `homepage`: Url of the theme.
- `screenshot`: Path to a screenshot of the theme example site.
- `description`: A single line theme description, asciidoc markup can be used.
- `longDescription`: Free length site description, asciidoc markup can be used.
- `documentation`: Theme documentation, asciidoc markup should be used.

[source, nix]
.Example of a simple theme meta.nix
----
{
  id = "showcase";
}
----

[source, nix]
.Example of a theme meta.nix with multiple attributes
----
{ lib }:
{
  id          = "showcase";
  name        = "Showcase";
  license     = lib.licenses.mit;
  demoPage    = https://styx-static.github.io/styx-theme-showcase;
  homepage    = https://github.com/styx-static/styx-theme-showcase;
  screenshot  = ./screen.png;
  description = "A theme to show Styx main functionalities.";
}
----

IMPORTANT: Themes *must* define a `meta.nix` with an `id` attribute.

NOTE: `meta.nix` can be an attribute set or a function, if it is a function it will be called with an attribute set argument containing `lib`.

[[themes.files]]
=== Files

The `files` directory holds the static files provided by the theme. Every file in in this directory will be copied in the generated site.

NOTE: If multiple themes are enabled, every theme `file` directory contents will be copied to the generated site.

==== Special files

Styx automatically convert `sass`, `scss` and `less` files to css during site generation.

[[themes.library]]
=== Library

Themes can provide a function library that can be used in `site.nix` or in templates.

To provide a library, a theme must have a `lib.nix` file containing an attribute set of functions.

To be sure a theme library functions will not override default functions it is best practice to put the functions in a dedicated namespace, `theme.ID` where `ID` is the theme id as a natural choice.

[source, nix]
.Example of a theme lib.nix
----
{ lib }:
{
  theme.my-theme = {
    foo = x: "foo called with ${builtins.toString x}";
  };
}
----

NOTE: `lib.nix` can be an attribute set or a function, if it is a function it will be called with an attribute set argument containing `lib`.

include::themes/templates.adoc[]

[[themes.combining]]
=== Combining Themes

In `site.nix`, themes are declared as a list. If multiple themes in the list provide the same file or template, the last theme in the list to declare it will be used.

This allows to build new themes based on other themes, like the showcase theme is built on the base of the generic-templates theme.

To combine a theme it is just needed to declare multiple themes in `site.nix`. If multiple themes define the same asset, asset from the later theme in the list will be used.

[source, nix]
.Combining generic-templates and my-theme
----
themes = [
  styx-themes.generic-templates
  ./themes/my-theme
];
----

If generic-templates and my-theme both defines `templates/partials/content.nix`, the one from my-theme will be used. +
Any used asset that is not defined in my-theme, will be used from generic-templates.

NOTE: There is no limit in the number of theme that can be combined.

