== Blog Tutorial

=== Preparation

Install styx.


=== Create a new site

First, we will use the styx `new` command to generate files required for a new site:

[source, shell]
----
$ styx new site my-blog
$ cd my-blog
----

The `styx new site` will generate the following file structure:

[source, shell]
----
my-blog
├── conf.nix
├── data
├── readme.md
├── site.nix
└── themes
----

The most important file is `site.nix`.

=== Declare Themes

In `site.nix`, find the line declaring the themes:

----
  themes = [
    
  ];
----

And change it to the following to load the Hyde and generic templates themes.

----
  themes = [
    styx-themes.generic-templates
    styx-themes.hyde
  ];
----

=== Create an index page

Next, we will create an index page, in `site.nix` find the line declaring the `pages` attribute set:

----
  pages = rec {
    
  };
----

Lets declare an index page.

----
  pages = rec {
    index = {
      title    = "Home";
      path     = "/index.html";
      template = templates.index;
      layout   = templates.layout;
    };
  };
----

We can preview the site by running the following command:

----
$ styx preview
----

And accessing to 127.0.0.1:8080 with a browser.


=== Create content

We have an empty index page!
Lets generate some data and create pages in our new blog.
Styx has a `gen-sample-data` subcommand that will generate some data for us:

----
$ styx gen-sample-data
----

This generate the following data:

----
----

Then we can load that data in `site.nix` `data` section. Find the line declaring the `data` set:

----
  data = {
    
  };
----

And lets load our sample data:

----
  data = {
    posts = lib.sortBy "date" "dsc" (lib.loadDir { dir = ./data/sample/posts; });
  };
----

=== Add some pages

Having data is not enough, we need to create pages from the data.

In the `pages` set, lets add the posts:

----
  pages = rec {
    index = {
      title    = "Home";
      path     = "/index.html";
      template = templates.index;
      layout   = templates.layout;
    };

    posts = lib.mkPageList {
      data       = data.posts;
      pathPrefix = "/posts/";
      template   = templates.post.full;
      layout     = templates.layout;
    };
  };
----

Lets preview our site again:

----
$ styx preview
----

Posts have been generated, but they dont appear yet on the top page. Let's fix that in the next step.

=== Index page revisited

The Hyde design is designed so the most recent `n` posts appears on the index page, and older posts are on archive pages. +
So we need to split our posts between the index and archive pages.

There is a `mkSplit` function that does just that, so we will adapt our index page declaration to use it:

----
  pages = rec {
    index = lib.mkSplit {
      title        = "Home";
      basePath     = "/index";
      itemsPerPage = conf.theme.itemsPerPage;
      template     = templates.index;
      data         = posts;
      layout       = templates.layout;
    };

    posts = lib.mkPageList {
      data       = data.posts;
      pathPrefix = "/posts/";
      template   = templates.post.full;
      layout     = templates.layout;
    };
  };
----

Lets preview our site again:

----
$ styx preview
----

Posts are listed on the index pages, and split between mutiple pages.


=== Adding pages


=== Adding an atom feed


=== Improvements

==== Multipages handling

One of the sample data is using multipages, but `mkPageList` only generates the first page of multipages posts.

Lets generate the subpages:

----
  pages = rec {
    index = lib.mkSplit {
      title        = "Home";
      basePath     = "/index";
      itemsPerPage = conf.theme.itemsPerPage;
      template     = templates.index;
      data         = posts;
      layout       = templates.layout;
    };

    posts = lib.mkPageList {
      data       = data.posts;
      pathPrefix = "/posts/";
      template   = templates.post.full;
      layout     = templates.layout;
    };

    postsMultiTail = lib.mkMultiTail {
      data       = data.posts;
      pathPrefix = "/posts/";
      template   = templates.post.full;
      layout     = templates.layout;
    };
  };
----

==== Customizing our site

The Hyde theme provide some configuration options that can be used to change our blog.

The following command will generate a documentation for our site including the avalaible theme options:

----
$ styx site-doc
----

Lets try do some changes to Hyde options.
Open `conf.nix` at site root and find the following line:

----
  theme = {
  };
----

And change it to:

----
  theme = {
    site.title = "My Styx Blog";
    colorScheme = "0d";
    itemsPerPage = 5;
  };
----

Let's preview our site and see if it changed.


==== Cleaning up

All of our pages are declaring the same `layout`. +
It is possible to set attributes to every page when converting our page set to a page list.

In `site.nix` find:

----
  pagesList = lib.pagesToList { inherit pages; };
----

Let's add the default layout here:

----
  pagesList = lib.pagesToList { inherit pages; default = { layout = templates.layout; }; };
----

And remove all the `layout` declarations of our pages:

----
  pages = rec {
    index = lib.mkSplit {
      title        = "Home";
      basePath     = "/index";
      itemsPerPage = conf.theme.itemsPerPage;
      template     = templates.index;
      data         = posts;
    };

    posts = lib.mkPageList {
      data       = data.posts;
      pathPrefix = "/posts/";
      template   = templates.post.full;
    };

    postsMultiTail = lib.mkMultiTail {
      data       = data.posts;
      pathPrefix = "/posts/";
      template   = templates.post.full;
    };
  };
----
