#! /usr/bin/env bash

# Run the tests, should be run before every commit

# usage

#  ./scripts/run-tests

realpath() {
  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
styxDir="$(dirname scriptDir)"
testsDir=$(realpath "$styxDir/tests")
nixpkgsDir=$(realpath "$styxDir/nixpkgs")

echo ""

echo "Main tests:"
if nix-build "$testsDir" --no-out-link --show-trace; then
  echo "  success"
else
  echo "  failure"
  exit 1
fi

echo ""

echo "Library tests:"

if [ "$(nix-instantiate --eval -A success $testsDir/lib.nix --read-write-mode)" = "true" ]; then
  echo "  success";
else
  cat $(nix-build --no-out-link -A report $testsDir/lib.nix)
  exit 1
fi

echo ""
echo "Finished"
