#! /usr/bin/env sh

# Run the tests, should be run before every commit

# usage

#  ./scripts/run-tests


scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
testsDir=$(realpath "$scriptDir/../tests")
nixpkgsDir=$(realpath "$scriptDir/../nixpkgs")

main=$(nix-build "$testsDir" --no-out-link)

echo ""

echo "Main tests:"
if [ $? -ne 0 ]; then
  echo "  failure"
else
  echo "  success"
fi

echo ""

echo "Library tests:"

cat $(nix-build --no-out-link -A report $testsDir/lib.nix)

echo ""
echo "Finished"
