#! /usr/bin/env bash

# Run the tests, should be run before every commit

# usage

#  ./scripts/run-tests


scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
styxDir="$(dirname scriptDir)"
testsDir=$(readlink -f -- "$styxDir/tests")
nixpkgsDir=$(readlink -f -- "$styxDir/nixpkgs")

echo ""

echo "Main tests:"
if nix-build "$testsDir" --no-out-link; then
  echo "  success"
else
  echo "  failure"
  exit 1
fi

echo ""

echo "Library tests report:"

cat $(nix-build --no-out-link -A report $testsDir/lib.nix)

echo ""
echo "Finished"
