#! /usr/bin/env bash

# Update documentation styx-themes chapter

echo "Generating themes documentation."
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
baseDir=$(dirname "$scriptDir")
path=$(nix-build "$scriptDir/themes-doc.nix" --no-out-link "$@")
if [ $? -ne 0 ]; then
  echo "Error: build failed"
  exit 1
fi

target=$(readlink -f -- "$baseDir/src/doc/")
cp $path/themes-generated.adoc $target/styx-themes-generated.adoc --no-preserve=all
cp $path/imgs/* $target/imgs/ --no-preserve=all
echo "Themes documentation updated!"


echo "Generating library documentation."
path=$(nix-build "$scriptDir/library-doc.nix" --no-out-link "$@")
if [ $? -ne 0 ]; then
  echo "Error: build failed"
  exit 1
fi
target=$(readlink -f -- "$baseDir/src/doc/")
cp $path/library-generated.adoc $target/library-generated.adoc --no-preserve=all
echo "Library documentation updated!"
