name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.1

    - uses: cachix/install-nix-action@v17
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.9.0pre20220519_5aeda91/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build
      run: nix-build

    - name: Test
      run: nix run .#run-tests --show-trace
